version: v1
language: LSC
labels:
  - {id: 0,  name: "hola"}
  - {id: 1,  name: "adios"}
  - {id: 2,  name: "gracias"}
  - {id: 3,  name: "por_favor"}
  - {id: 4,  name: "si"}
  - {id: 5,  name: "no"}
  - {id: 6,  name: "yo"}
  - {id: 7,  name: "tu"}
  - {id: 8,  name: "mi"}
  - {id: 9,  name: "tuyo"}
  - {id: 10, name: "que"}
  - {id: 11, name: "como"}
  - {id: 12, name: "bien"}
  - {id: 13, name: "mal"}
  - {id: 14, name: "ayuda"}
  - {id: 15, name: "repetir"}
  - {id: 16, name: "lento"}
  - {id: 17, name: "rapido"}
  - {id: 18, name: "entender"}
  - {id: 19, name: "no_entender"}
  - {id: 20, name: "nombre"}
  - {id: 21, name: "cual"}
  - {id: 22, name: "hoy"}
  - {id: 23, name: "manana"}
  - {id: 24, name: "casa"}
  - {id: 25, name: "universidad"}
  - {id: 26, name: "amigo"}
  - {id: 27, name: "familia"}
  - {id: 28, name: "comida"}
  - {id: 29, name: "agua"}
